name: Deploy Functions

on:
  push:
    tags:
      - "fn/v*"

jobs:
  deploy-functions:
    name: Deploy Functions
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - run: npm ci

      - run: npm run build

      - run: npm test

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - run: npx firebase-tools deploy --only functions --force
